### ISSUE TITLE
Bug: Temperature converter demo has an error in console

### ISSUE THREAD

**Issue by JackEdwardLyons** [statelyai/xstate#3098]
### Description

When updating the inputs in the temperature converter demo, the following error occurs:

```
Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
    at input
    at label
    at section
    at TempConv (https://68083.csb.app/src/index.tsx:27:46)
    at App
```

### Expected result

No error in the console.

### Actual result

Error in the console:

```
Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
    at input
    at label
    at section
    at TempConv (https://68083.csb.app/src/index.tsx:27:46)
    at App
```

### Reproduction

https://codesandbox.io/s/7guis-temperature-68083?from-embed

### Additional context

Simpy update the inputs in the demo and check the console to see the error.

**Comment by davidkpiano** [comment]
This has now been fixed; not related to XState:

```diff
-value={C}
+value={C ?? '')

// etc.
```
