### ISSUE TITLE
Bug: Errors thrown by @xstate/test@alpha with Playwright do not contain information about failed paths

### ISSUE THREAD

**Issue by Devessier** [statelyai/xstate#3435]
### Description

When using @xstate/test@alpha with Playwright, if assertion errors are thrown, additional information from @xstate/test about paths that failed won't be logged by Playwright (the state in which assertions failed, events sent before errors occurred, etc.).

### Expected result

I would expect information about paths that fail (visited states, sent events, state in which an error occurred).

### Actual result

Currently these information are not shown.

![Logs without path information](https://user-images.githubusercontent.com/29370468/176893776-ff626bac-59f1-4012-b11b-a28b906d6193.png)

### Reproduction

https://github.com/Devessier/xstate-test-playwright-error-repro

### Additional context

As noted in Node.js documentation (https://nodejs.org/api/errors.html#errormessage):

> changing [error.message] after the Error object is created may not change the first line of the stack trace
> (for example, when error.stack is read before this property is changed)

It seems that Playwright reads `error.stack` before @xstate/test overrides `error.message`, which does not update `error.stack`.

**Comment by davidkpiano** [comment]
Working on a potential feature/fix for this; what do you think about this?

In the new feature, you'd be able to add an error listener to `model.onError(error => {...})` and output that error however you'd like.

Ultimately, this is a limitation of Playwright, and not of `@xstate/test`, since both are fighting over control over the error message.

![CleanShot 2022-07-03 at 08 13 12](https://user-images.githubusercontent.com/1093738/177039174-e8ebe3e7-d3ab-4653-8764-c5c6ac9b6e1f.png)

**Comment by Andarist** [comment]
Like @Devessier has mentioned - the problem might be in tampering with the `err.message`. We probably should never do this, I've rechecked a couple of libraries and some of them actually do it but I'd consider this to be an anti-pattern and something that should be avoided if possible. 

With recent versions of JS we can use make of [`cause`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause) to achieve quite nice results:

```
> new Error('Error has happened in this path', { cause: new Error('muahduashduhdahu, world burns')  })
Error: Error has happened in this path
    at REPL4:1:1
    at Script.runInThisContext (node:vm:129:12)
    ... 7 lines matching cause stack trace ...
    at REPLServer.Interface._line (node:readline:864:8) {
  [cause]: Error: muahduashduhdahu, world burns
      at REPL4:1:55
      at Script.runInThisContext (node:vm:129:12)
      at REPLServer.defaultEval (node:repl:566:29)
      at bound (node:domain:421:15)
      at REPLServer.runBound [as eval] (node:domain:432:12)
      at REPLServer.onLine (node:repl:893:10)
      at REPLServer.emit (node:events:538:35)
      at REPLServer.emit (node:domain:475:12)
      at REPLServer.Interface._onLine (node:readline:487:10)
      at REPLServer.Interface._line (node:readline:864:8)
}
```

The `cause` isn't formatted as nicely in Chrome but it's probably temporary. FireFox already handles this nicely too:
```
Error: Error has happened in this path
    <anonymous> debugger eval code:1
Caused by: Error: muahduashduhdahu, world burns
    <anonymous> debugger eval code:1
```

**Comment by davidkpiano** [comment]
@Andarist Does that work in Node with Playwright? (I'll try it out soon)

**Comment by Andarist** [comment]
I'm not sure - don't have a setup for this at hand to try it out quickly. It all depends on how they pass around the received objects to the console. If they just pass them to the console without tampering then it should work out of the box (at least in versions of node that support `.cause`)

**Comment by davidkpiano** [comment]
> I'm not sure - don't have a setup for this at hand to try it out quickly. It all depends on how they pass around the received objects to the console. If they just pass them to the console without tampering then it should work out of the box (at least in versions of node that support `.cause`)

Just tried it; it doesn't quite work.

```ts
throw new Error(
  err.message, // original error
  {
    cause: formatPathTestResult(path, testPathResult, this.options)
  }
);
```

**Output:**
```
  1) tests/fail.spec.ts:21:3 › Reaches state "Page loaded": NEXT ===================================

    Error: expect(received).toBeVisible()
    Call log:
      - expect.toBeVisible with timeout 5000ms
      - waiting for selector "text="Invalid text""


        at TestModel.<anonymous> (/Users/davidkpiano/Code/xstate-v4/packages/xstate-test/lib/TestModel.js:333:31)
        at step (/Users/davidkpiano/Code/xstate-v4/packages/xstate-test/lib/TestModel.js:44:23)
        at Object.throw (/Users/davidkpiano/Code/xstate-v4/packages/xstate-test/lib/TestModel.js:25:53)
        at rejected (/Users/davidkpiano/Code/xstate-v4/packages/xstate-test/lib/TestModel.js:17:65)
```

```ts
throw new Error(
  formatPathTestResult(path, testPathResult, this.options),
  {
    cause: err // original error
  }
);
```

**Output:**

```

  1) tests/fail.spec.ts:21:3 › Reaches state "Page loaded": NEXT ===================================

    Error: 
    Path:
        State: {"value":"loading"}
        Event: {"type":"NEXT"}

        State: {"value":"Page loaded"} via {"type":"NEXT"}

        at TestModel.<anonymous> (/Users/davidkpiano/Code/xstate-v4/packages/xstate-test/lib/TestModel.js:333:31)
        at step (/Users/davidkpiano/Code/xstate-v4/packages/xstate-test/lib/TestModel.js:44:23)
        at Object.throw (/Users/davidkpiano/Code/xstate-v4/packages/xstate-test/lib/TestModel.js:25:53)
        at rejected (/Users/davidkpiano/Code/xstate-v4/packages/xstate-test/lib/TestModel.js:17:65)
```

**Comment by Andarist** [comment]
Hm, I have somewhat positive results (although not ideal) with the second variant:
```ts
throw new Error(
  formatPathTestResult(path, testPathResult, this.options),
  {
    cause: err // original error
  }
);
```

`cause` is irrelevant here though as they completely take over logging and they don't support `.cause` yet. I see the information related to my thrown error logged in the console and the Playwright's information is not lost either

**Test body**
```ts
try {
	await expect(page.locator('.new-todo')).not.toBeVisible();
} catch (err) {
	throw new (Error as any)('my custom error', { cause: new Error('completely different err') });
}
```

**Output**
```
Running 1 test using 1 worker
  1) [chromium] › example.spec.ts:14:2 › New Todo › should allow me to add todo items ==============

    Timeout of 5000ms exceeded.

    Error: my custom error

      16 |                      await expect(page.locator('.new-todo')).not.toBeVisible();
      17 |              } catch (err) {
    > 18 |                      throw new (Error as any)('my custom error', { cause: new Error('completely different err') });
         |                            ^
      19 |              }
      20 |
      21 |              console.log('leeets continue')

        at /playwright-test/tests/example.spec.ts:18:10

    Pending operations:
      - expect.toBeVisible at tests/example.spec.ts:16:48



  1 failed
    [chromium] › example.spec.ts:14:2 › New Todo › should allow me to add todo items ===============
```
